### ISSUE TITLE
License center IDs vary based on appointment type

### ISSUE THREAD

**Issue by mooey5775** [qdbp/mvc-whackamole#1]
Hi - thanks for your work on this project!

I think I found an issue with any appointment type that is not a License/Non-Driver ID renewal. The MVC location IDs listed in `MVC.kt` seem specific to that appointment type. If I make a request on the MVC website for a REAL ID appointment in Wayne, it seems to request location ID 140 instead of 118. Additionally, this location ID varies for any other type of appointment in any MVC location.

**Comment by mooey5775** [comment]
Ignore this, there are many exceptions.

<s>
I've looked into it some more and it seems like the relative ordering of license center IDs (have not checked vehicle centers yet) remains constant across appointment types.

This means that each appointment type has a license center `offset` (license/non-driver id renewal seems to start at 101, real id starts at 124), after which license centers are given IDs sequentially in the same order.

Hopefully this will save on some code complexity/scraping.
</s>

**Comment by qdbp** [comment]
Looking into this -- that's a pain.

**Comment by qdbp** [comment]
Confirmed -- working on this. Thanks a lot of finding this one.

**Comment by qdbp** [comment]
@mooey5775 ~~The `offset` still works, I think, it's just that the base sequence has gaps in it. However, I think these gaps are the same for every appointment type, so I'll just be able to write the id as `getIdForApptType` or similar.~~

Lol jk you were right the entire center/type matrix needs to be hardcoded.

**Comment by qdbp** [comment]
fixed in 1.2
